name: ctools
version: 2.0.0
main: castro.ctools.Plugin
depend: [Vault, Base_cPlugin, Multiverse-Core, WorldGuard, WorldEdit]
commands:
  modreq:
  clearscreen:
    description: Czysci chat
    aliases: [cls]
    usage: /clearscreen
  setrank:
    description: Zmienia range podanego gracza
    aliases: [rank]
    usage: /setrank <nick> <rank>
  sudo:
    description: Wykonuje komende jako inny gracz
    aliases: []
    usage: /sudo <nick> <target command>
  modbroadcast:
    description: Wysyla wiadomosc tylko do modow
    aliases: [mb, ho]
    usage: /modbroadcast <msg>
  contest:
    description: Komenda na udzial w konkursie
    aliases: [konkurs]
    usage: /contest
  list:
    aliases: [who]
  searchplayerstotrack:
  limitmobs: